function[figure_freq] = get_ZPm_Tx_freq(X,...
                                        YPn,...
                                        symmetries,...
                                        matching_mask_detailed,...
                                        fixed_matching_mask_detailed,...
                                        fixed_matching_elements,...
                                        tuning_mask_detailed,...
                                        matching_mask,...
                                        fixed_matching_mask,...
                                        tuning_mask,...
                                        mutual_mask,...
                                        matching_load_string,...
                                        tuning_load_string,...
                                        port_order,...
                                        omega,...
                                        z0,...
                                        Q_val)

    freq                 = omega/(2*pi);
    freq_range           = linspace(freq * 0.8, freq * 1.2, 5000); 
    [~, freq_idx]        = min(abs(freq_range - freq)); 
    freq_range(freq_idx) = freq; 
    omega_range          = freq_range*2*pi;
      
    M                                  = nonzeros(matching_mask);
    F                                  = nonzeros(fixed_matching_mask);
    N                                  = nonzeros(tuning_mask);
    D1                                 = nonzeros(mutual_mask(:,1));
    D2                                 = nonzeros(mutual_mask(:,2));
    D1                                 = ismember(N,D1);
    D2                                 = ismember(N,D2);
    [M,F,N]                            = map_to_local(M,F,N);
    M                                  = sort([M(:); F(:)]);
    D1                                 = N(D1);
    D2                                 = N(D2);
    all_values                         = [D1 D2];                     
    [~, sort_idx]                      = sort(all_values);  
    ranks                              = zeros(size(all_values));           
    ranks(sort_idx)                    = 1:length(all_values); 
    mapped_D1                          = ranks(1:length(D1));
    mapped_D2                          = ranks(length(D1)+1:end);
    length_matching_network            = unique(max(port_order));
    M_detailed                         = nonzeros(matching_mask_detailed);
    F_detailed                         = nonzeros(fixed_matching_mask_detailed);
    N_detailed                         = nonzeros(tuning_mask_detailed);
    [M_detailed,F_detailed,N_detailed] = map_to_local(M_detailed,F_detailed,N_detailed);
    MN_detailed                        = sort([M_detailed(:); N_detailed(:)]);
    MF_detailed                        = sort([M_detailed(:); F_detailed(:)]);

    lumped_elements                  = X(symmetries); 
    all_elements                     = zeros(numel(M_detailed)+numel(F_detailed)+numel(N_detailed),1);
    all_elements(MN_detailed)        = lumped_elements;
    all_elements(F_detailed)         = fixed_matching_elements(F_detailed);
    matching_elements                = all_elements(MF_detailed);
    Q_matching_elements              = Q_val(MF_detailed);
    true_tuning_elements             = all_elements(N_detailed);
    Q_true_tuning_elements           = Q_val(N_detailed);
    is_capacitor_parallel            = strcmpi(matching_load_string, 'capacitorParallel');
    is_inductor_parallel             = strcmpi(matching_load_string, 'inductorParallel');
    is_resistor_parallel             = strcmpi(matching_load_string, 'resistorParallel');
    is_capacitor_series              = strcmpi(matching_load_string, 'capacitorSeries');
    is_inductor_series               = strcmpi(matching_load_string, 'inductorSeries');
    is_resistor_series               = strcmpi(matching_load_string, 'resistorSeries');
    is_capacitor                     = strcmpi(tuning_load_string, 'capacitor');
    is_inductor                      = strcmpi(tuning_load_string, 'inductor');
    is_resistor                      = strcmpi(tuning_load_string, 'resistor');
    is_mutual_inductor               = strcmpi(tuning_load_string, 'mutual_inductor');
    is_mutual_inductance_coefficient = strcmpi(tuning_load_string, 'mutual_inductance_coefficient');
    mutual_inductance_coefficients   = lumped_elements(end-sum(is_mutual_inductance_coefficient)+1:end);
    mutual_inductances               = true_tuning_elements(is_mutual_inductor);

    ZPm_plot = zeros(size(M,1),size(M,1),length(freq_range));
    SPm_plot = zeros(size(M,1),size(M,1),length(freq_range));

    for freq_id = 1:length(freq_range)

        [YPm,~,~] = tune(true_tuning_elements,...
                         omega_range(freq_id),...
                         Q_true_tuning_elements,...
                         is_capacitor,...
                         is_inductor,...
                         is_mutual_inductor,...
                         is_resistor,...
                         YPn,...
                         D1,...
                         D2,...
                         mutual_inductance_coefficients,...
                         mutual_inductances,...
                         mapped_D1,...
                         mapped_D2,...
                         N,...
                         M);
    
        % Matching Elements
        [SPm,ZPm,~] = match(YPm,...
                            YPm,...
                            z0,...
                            length_matching_network,...
                            port_order,...
                            is_capacitor_parallel,...
                            is_inductor_parallel,...
                            is_resistor_parallel,...
                            is_capacitor_series,...
                            is_inductor_series,...
                            is_resistor_series,...
                            matching_elements,...
                            Q_matching_elements,...
                            omega_range(freq_id));

        ZPm_plot(:,:,freq_id) = ZPm;
        SPm_plot(:,:,freq_id) = SPm;
    end

    figure_freq.ZPm_plot_Rx = [];
    figure_freq.SPm_plot_Rx = [];
    figure_freq.ZPm_plot_Tx = ZPm_plot;
    figure_freq.SPm_plot_Tx = SPm_plot;
    figure_freq.freq_range  = freq_range;
    figure_freq.freq_idx    = freq_idx;

end