function[options_PSO1, options_PSO2] = co_simulation_optimization_settings()  
    
    % PSO Options
    options_PSO1 = optimoptions('particleswarm', ...
                                'SwarmSize', 300, ...
                                'MaxIterations', 500, ...
                                'FunctionTolerance',1e-5,...
                                'Display', 'none', ...
                                'UseParallel', false, ...
                                'InertiaRange', [0.5, 1.2], ...  
                                'SelfAdjustmentWeight', 1.3, ... 
                                'SocialAdjustmentWeight', 1.5, ...
                                'MaxStallIterations', 50, ...
                                'ObjectiveLimit', 1e-8);

    options_PSO2 = options_PSO1;
    options_PSO2.SwarmSize = 300;
    options_PSO2.MaxIterations = 400;
    options_PSO2.FunctionTolerance = 1e-2;
    options_PSO2.Display = 'iter';

    % options_fmincon = optimoptions('fmincon', ...
    %                                'Display', 'iter', ...
    %                                'Algorithm', 'interior-point', ...
    %                                'MaxIterations', 50000, ...
    %                                'MaxFunctionEvaluations', 500000, ...
    %                                'ObjectiveLimit', 1e-5, ...
    %                                'ConstraintTolerance', 1e-20, ...
    %                                'OptimalityTolerance', 1e-20, ...
    %                                'StepTolerance', 1e-20, ...
    %                                'ScaleProblem', true, ...
    %                                'SpecifyObjectiveGradient', false, ...
    %                                'FiniteDifferenceType', 'central', ...                                   
    %                                'FiniteDifferenceStepSize', 1e-14, ...
    %                                'DiffMinChange', 1e-14);


end