function [M_cal,...
          YPm_Tx,...
          ZPm,...
          SPm,...
          SP_check,...
          phi_lumped_elements] = calibration_tune_match_TxRx_decouple_and_Rx_preampdecouple(X,...
                                                                                            YPn,...
                                                                                            symmetries,...
                                                                                            match_split,...
                                                                                            mask_detailed_split,...
                                                                                            matching_mask_detailed,...
                                                                                            fixed_matching_mask_detailed,...
                                                                                            fixed_matching_elements,...
                                                                                            tuning_mask_detailed,...
                                                                                            matching_mask,...
                                                                                            fixed_matching_mask,...            
                                                                                            tuning_mask,...
                                                                                            mutual_mask,...
                                                                                            matching_load_string,...
                                                                                            tuning_load_string,...
                                                                                            port_order,...
                                                                                            omega,...
                                                                                            z0,...
                                                                                            preamp_res,...
                                                                                            detune_res, ...
                                                                                            Q_val)

    M                                  = nonzeros(matching_mask);
    F                                  = nonzeros(fixed_matching_mask);
    N                                  = nonzeros(tuning_mask);
    D1                                 = nonzeros(mutual_mask(:,1));
    D2                                 = nonzeros(mutual_mask(:,2));
    D1                                 = ismember(N,D1);
    D2                                 = ismember(N,D2);
    [M,F,N]                            = map_to_local(M,F,N);
    M                                  = sort([M(:); F(:)]);
    D1                                 = N(D1);
    D2                                 = N(D2);
    all_values                         = [D1 D2];                     
    [~, sort_idx]                      = sort(all_values);  
    ranks                              = zeros(size(all_values));           
    ranks(sort_idx)                    = 1:length(all_values); 
    mapped_D1                          = ranks(1:length(D1));
    mapped_D2                          = ranks(length(D1)+1:end);
    length_matching_network            = unique(max(port_order(:)));
    M_detailed                         = nonzeros(matching_mask_detailed);
    F_detailed                         = nonzeros(fixed_matching_mask_detailed);
    N_detailed                         = nonzeros(tuning_mask_detailed);
    [M_detailed,F_detailed,N_detailed] = map_to_local(M_detailed,F_detailed,N_detailed);
    MN_detailed                        = sort([M_detailed(:); N_detailed(:)]);
    MF_detailed                        = sort([M_detailed(:); F_detailed(:)]);

    lumped_elements                  = X(symmetries); 
    Rx_elems_match                   = mask_detailed_split==1 | mask_detailed_split==3;
    Tx_elems_match                   = mask_detailed_split==3;
    RxM                              = match_split==1 | match_split==3;
    RxM_det                          = match_split==1;
    TxM                              = match_split==3;
    all_elements                     = zeros(numel(M_detailed)+numel(F_detailed)+numel(N_detailed),1);
    all_elements(MN_detailed)        = lumped_elements;
    all_elements(F_detailed)         = nonzeros(fixed_matching_elements);
    true_tuning_elements             = all_elements(N_detailed);
    Q_true_tuning_elements           = Q_val(N_detailed);
    matching_elementsRx              = all_elements(MF_detailed(Rx_elems_match(MF_detailed)));
    matching_elementsTx              = all_elements(MF_detailed(Tx_elems_match(MF_detailed)));
    Q_matching_elementsRx            = Q_val(MF_detailed(Rx_elems_match(MF_detailed)));
    Q_matching_elementsTx            = Q_val(MF_detailed(Tx_elems_match(MF_detailed)));
    matching_load_stringRx           = matching_load_string(:,RxM);
    matching_load_stringTx           = matching_load_string(:,TxM);
    port_orderRx                     = port_order(:,RxM);
    port_orderRx                     = port_orderRx(:);
    port_orderTx                     = port_order(:,TxM);
    port_orderTx                     = port_orderTx(:);
    is_capacitor_parallelRx          = strcmpi(matching_load_stringRx(:), 'capacitorParallel');
    is_inductor_parallelRx           = strcmpi(matching_load_stringRx(:), 'inductorParallel');
    is_resistor_parallelRx           = strcmpi(matching_load_stringRx(:), 'resistorParallel');
    is_capacitor_seriesRx            = strcmpi(matching_load_stringRx(:), 'capacitorSeries');
    is_inductor_seriesRx             = strcmpi(matching_load_stringRx(:), 'inductorSeries');
    is_resistor_seriesRx             = strcmpi(matching_load_stringRx(:), 'resistorSeries');
    is_capacitor_parallelTx          = strcmpi(matching_load_stringTx(:), 'capacitorParallel');
    is_inductor_parallelTx           = strcmpi(matching_load_stringTx(:), 'inductorParallel');
    is_resistor_parallelTx           = strcmpi(matching_load_stringTx(:), 'resistorParallel');
    is_capacitor_seriesTx            = strcmpi(matching_load_stringTx(:), 'capacitorSeries');
    is_inductor_seriesTx             = strcmpi(matching_load_stringTx(:), 'inductorSeries');
    is_resistor_seriesTx             = strcmpi(matching_load_stringTx(:), 'resistorSeries');
    is_capacitor                     = strcmpi(tuning_load_string, 'capacitor');
    is_inductor                      = strcmpi(tuning_load_string, 'inductor');
    is_resistor                      = strcmpi(tuning_load_string, 'resistor');
    is_mutual_inductor               = strcmpi(tuning_load_string, 'mutual_inductor');
    is_mutual_inductance_coefficient = strcmpi(tuning_load_string, 'mutual_inductance_coefficient');
    mutual_inductance_coefficients   = lumped_elements(end-sum(is_mutual_inductance_coefficient)+1:end);
    mutual_inductances               = true_tuning_elements(is_mutual_inductor);

    % Tuning Elements
    [YPm,YPm_loss,M_tune] = tune(true_tuning_elements,...
                                 omega,...
                                 Q_true_tuning_elements,...
                                 is_capacitor,...
                                 is_inductor,...
                                 is_mutual_inductor,...
                                 is_resistor,...
                                 YPn,...
                                 D1,...
                                 D2,...
                                 mutual_inductance_coefficients,...
                                 mutual_inductances,...
                                 mapped_D1,...
                                 mapped_D2,...
                                 N,...
                                 M);   

    % Apply detuning
    Rxdet = 1/detune_res*eye(size(nonzeros(RxM_det),1));
    YPm_Tx = YPm;
    YPm_Tx(RxM_det,RxM_det) = YPm_Tx(RxM_det,RxM_det)+Rxdet;
    ZPn_Tx = inv(YPm_Tx);
    
    MTx                        = size(nonzeros(TxM),1);
    M_detune_Tx                = zeros(length(M),MTx);
    M_detune_Tx(TxM,1:MTx)     = ZPn_Tx(TxM,TxM);
    M_detune_Tx(RxM_det,1:MTx) = ZPn_Tx(RxM_det,TxM);
    M_detune_Tx                = M_detune_Tx/ZPn_Tx(TxM,TxM);

    % Switch to de-tuned mode
    YPm_Rx = YPm;
    YPm_Tx = YPm(TxM,TxM)-YPm(TxM,RxM_det)/(YPm(RxM_det,RxM_det)+Rxdet)*YPm(RxM_det,TxM);

    % Add tuning elements to loss
    YPm_loss_Rx = YPm_loss;
    YPm_loss_Tx = YPm_loss(TxM,TxM)-YPm_loss(TxM,RxM_det)/(YPm_loss(RxM_det,RxM_det)+Rxdet)*YPm_loss(RxM_det,TxM);

    % Model preamplifier effect
    [M_match_Rx,...
     M_decouple_Rx,...
     SP_check,...
     ZP_check,...
     ZP_check_loss] = preamplifier_match(YPm_Rx,...
                                         YPm_loss_Rx,...
                                         preamp_res,...
                                         z0,...
                                         length_matching_network,...
                                         port_orderRx,...
                                         is_capacitor_parallelRx,...
                                         is_inductor_parallelRx,...
                                         is_resistor_parallelRx,...
                                         is_capacitor_seriesRx,...
                                         is_inductor_seriesRx,...
                                         is_resistor_seriesRx,...
                                         matching_elementsRx,...
                                         Q_matching_elementsRx,...
                                         omega);

    SPs = np_z2s(inv(YPm_Tx),z0);
    % Model matching elements
    [SPm,ZPm,ZPm_loss] = match(YPm_Tx,...
                               YPm_loss_Tx,...
                               z0,...
                               length_matching_network,...
                               port_orderTx,...
                               is_capacitor_parallelTx,...
                               is_inductor_parallelTx,...
                               is_resistor_parallelTx,...
                               is_capacitor_seriesTx,...
                               is_inductor_seriesTx,...
                               is_resistor_seriesTx,...
                               matching_elementsTx,...
                               Q_matching_elementsTx,...
                               omega);   

    M_match_Tx = calibration_matching(SPs,SPm,z0);

    M_cal.rx = (M_tune*M_decouple_Rx)*M_match_Rx;
    M_cal.tx = (M_tune*M_detune_Tx)*M_match_Tx;

    phi_lumped_elements.Tx = diag(1/2*diag(abs(real(ZPm_loss-ZPm))).*(1./abs(diag(ZPm))).^2);
    phi_lumped_elements.Rx = 1/2*diag(abs(real(ZP_check_loss-ZP_check)).*(1./abs(ZP_check)).^2);

end