function [M_cal,...
          phi_lumped_elements,...
          YPm,...
          ZPm,...
          SPm,...
          SP_check] = calibration_match_preampdecouple(matching_elements,...
                                                       YPm,...
                                                       matching_load_string,...
                                                       port_order,...
                                                       omega,...
                                                       z0,...
                                                       preamp_res,...
                                                       Q_val)
    
    is_capacitor_parallel = strcmpi(matching_load_string, 'capacitorParallel');
    is_inductor_parallel  = strcmpi(matching_load_string, 'inductorParallel');
    is_resistor_parallel  = strcmpi(matching_load_string, 'resistorParallel');
    is_capacitor_series   = strcmpi(matching_load_string, 'capacitorSeries');
    is_inductor_series    = strcmpi(matching_load_string, 'inductorSeries');
    is_resistor_series    = strcmpi(matching_load_string, 'resistorSeries');

    length_matching_network = unique(max(port_order));

    YPm_loss = YPm;
    % Model preamplifier effect
    [M_match,...
     M_decouple,...
     SP_check,...
     ZP_check,...
     ZP_check_loss] = preamplifier_match(YPm,...
                                         YPm_loss,...
                                         preamp_res,...
                                         z0,...
                                         length_matching_network,...
                                         port_order,...
                                         is_capacitor_parallel,...
                                         is_inductor_parallel,...
                                         is_resistor_parallel,...
                                         is_capacitor_series,...
                                         is_inductor_series,...
                                         is_resistor_series,...
                                         matching_elements,...
                                         Q_val,...
                                         omega);

    % Model matching elements
    [SPm,ZPm,ZPm_loss] = match(YPm,...
                               YPm_loss,...
                               z0,...
                               length_matching_network,...
                               port_order,...
                               is_capacitor_parallel,...
                               is_inductor_parallel,...
                               is_resistor_parallel,...
                               is_capacitor_series,...
                               is_inductor_series,...
                               is_resistor_series,...
                               matching_elements,...
                               Q_val,...
                               omega);  

    M_cal = M_decouple*M_match;

    phi_lumped_elements.Tx = diag(1/2*diag(abs(real(ZPm_loss-ZPm))).*(1./abs(diag(ZPm))).^2);
    phi_lumped_elements.Rx = 1/2*diag(abs(real(ZP_check_loss-ZP_check))).*(1./abs(diag(ZP_check))).^2;
    phi_lumped_elements.Rx(isnan(phi_lumped_elements.Rx)) = 0;

end
