function [M_cal,...
          phi_lumped_elements,...
          YPm,...
          ZPm,...
          SPm] = calibration_match_decouple(matching_elements,...
                                            YPm,...
                                            matching_load_string,...
                                            port_order,...
                                            omega,...
                                            z0,...
                                            Q_val)
    
    is_capacitor_parallel = strcmpi(matching_load_string, 'capacitorParallel');
    is_inductor_parallel  = strcmpi(matching_load_string, 'inductorParallel');
    is_resistor_parallel  = strcmpi(matching_load_string, 'resistorParallel');
    is_capacitor_series   = strcmpi(matching_load_string, 'capacitorSeries');
    is_inductor_series    = strcmpi(matching_load_string, 'inductorSeries');
    is_resistor_series    = strcmpi(matching_load_string, 'resistorSeries');

    length_matching_network = unique(max(port_order));
    SPs = np_z2s(inv(YPm),z0);

    YPm_loss = YPm;
    % Model matching elements
    [SPm,ZPm,ZPm_loss] = match(YPm,...
                               YPm_loss,...
                               z0,...
                               length_matching_network,...
                               port_order,...
                               is_capacitor_parallel,...
                               is_inductor_parallel,...
                               is_resistor_parallel,...
                               is_capacitor_series,...
                               is_inductor_series,...
                               is_resistor_series,...
                               matching_elements,...
                               Q_val,...
                               omega);  
    
    M_cal = calibration_matching(SPs,SPm,z0);

    phi_lumped_elements.Tx = 1/2*diag(abs(real(ZPm_loss-ZPm))).*(1./abs(diag(ZPm))).^2;
    phi_lumped_elements.Rx = 1/2*diag(abs(real(ZPm_loss-ZPm))).*(1./abs(diag(ZPm))).^2;
    phi_lumped_elements.Rx(isnan(phi_lumped_elements.Rx)) = 0;

end
