function[M_cal,YPm,ZPm,SPm,SP_preamp] = co_simulation_Rx_no_optim(YPn,emc,RLC_org)
    % Get matching settings
    [matching_lumped_elements,...
     port_order,...
     matching_load_string] = co_simulation_matching_only_settings(RLC_org);

    % Calibrate fields
    [M_cal,...
     YPm,...
     ZPm,...
     SPm,...
     SP_preamp] = calibration_match_preampdecouple(matching_lumped_elements,...
                                                   YPn,...
                                                   matching_load_string(:),...
                                                   port_order(:),...
                                                   emc.omega,...
                                                   emc.Z0,...
                                                   emc.Preamp_res);
end