function[M_cal,YPm,ZPm,SPm,SP_preamp] = co_simulation_Rx_and_Tx_no_optim(YPn,emc,RLC_org)
    % Get matching settings
    [matching_lumped_elements,...
     port_order,...
     matching_load_string] = co_simulation_matching_only_settings(RLC_org);

    [match_split,...
     mask_detailed_split] = co_simulation_split_match_settings(RLC_org);

    % Calibrate fields
    [M_cal,...
     YPm,...
     ZPm,...
     SPm,...
     SP_preamp] = calibration_match_Tx_decouple_and_Rx_preampdecouple(matching_lumped_elements,...
                                                                     YPn,...
                                                                     match_split,...
                                                                     mask_detailed_split,...
                                                                     matching_load_string,...
                                                                     port_order,...
                                                                     emc.omega,...
                                                                     emc.Z0,...
                                                                     emc.Preamp_res,...
                                                                     emc.Detune_res);
end