function[M_cal,phi_lumped_elements,YPm,ZPm,SPm,SP_preamp] = co_simulation_Rx_and_TxRx_no_optim(YPn,emc,RLC_org,Q_val)
    % Get matching settings
    [matching_lumped_elements,...
     port_order,...
     matching_load_string] = co_simulation_matching_only_settings(RLC_org);

    [match_split,...
     mask_detailed_split] = co_simulation_split_match_settings(RLC_org);

    % Calibrate fields
    [M_cal,...
     YPm,...
     ZPm,...
     SPm,...
     SP_preamp,...
     phi_lumped_elements] = calibration_match_TxRx_decouple_and_Rx_preampdecouple(matching_lumped_elements,...
                                                                                  YPn,...
                                                                                  match_split,...
                                                                                  mask_detailed_split,...
                                                                                  matching_load_string,...
                                                                                  port_order,...
                                                                                  emc.omega,...
                                                                                  emc.Z0,...
                                                                                  emc.Preamp_res,...
                                                                                  emc.Detune_res,...
                                                                                  Q_val);
end