function[M_cal,phi_lumped_elements,YPm,ZPm,SPm,SP_preamp] = co_simulation_Tx_no_optim(YPn,emc,RLC_org,Q_val)
    % Get matching settings
    [matching_lumped_elements,...
     port_order,...
     matching_load_string] = co_simulation_matching_only_settings(RLC_org);

    % Calibrate fields
    [M_cal,...
     YPm,...
     ZPm,...
     SPm,...
     phi_lumped_elements] = calibration_match_decouple(matching_lumped_elements,...
                                                       YPn,...
                                                       matching_load_string(:),...
                                                       port_order(:),...
                                                       emc.omega,...
                                                       emc.Z0,...
                                                       Q_val);

    SP_preamp = [];

end