function[return_elements,M_cal,YPm,ZPm,SPm,SP_check,figure_freq] = co_simulation_Tx_optim(YPn,emc,RLC_org,RLC_tmd,options_PSO_1,options_PSO_2)
    
    % Tuning
    [elems_after_tuning,...
     tuning_elements,...
     mutual_elements,...
     tuning_mask,...
     matching_mask,...
     fixed_matching_mask,...
     mutual_mask,...
     coil_entity,...
     fval_tune] = runner_T(RLC_tmd,...
                           RLC_org,...
                           options_PSO_1,...
                           YPn,...
                           emc);
    
    % Tuning and Matching
    [elems_after_matching,...
     matching_load_string,...
     tuning_load_string,...
     port_order,...
     symmetries_all,...
     fixed_matching_mask_detailed,...
     fixed_matching_values,...
     matching_mask_detailed,...
     tuning_mask_detailed,...
     mutual_mask_detailed,...
     unique_indices_all,...
     lower_bound_mat,...
     upper_bound_mat,...
     fval_match] = runner_M_T(RLC_tmd,...
                              RLC_org,...
                              tuning_elements,...
                              mutual_elements,...
                              elems_after_tuning,...
                              coil_entity,...
                              matching_mask,...
                              fixed_matching_mask,...
                              tuning_mask,...
                              mutual_mask,...
                              options_PSO_1,...
                              YPn,...
                              emc,...
                              fval_tune);
    
    % Tuning and Matching and Decoupling
    [elements_after_tuning_matching_decoupling,...
     all_matching_load_string,...
     all_port_order,...
     all_tuning_load_string,...
     all_tuning_mask_detailed,...
     all_matching_mask_detailed,...
     all_fixed_matching_mask_detailed,...
     all_fixed_matching_values,...
     all_matching_mask,...
     all_fixed_matching_mask,...
     all_tuning_mask,...
     all_mutual_mask,...
     symmetries_all] = runner_M_T_D(matching_load_string,...
                                     tuning_load_string,...
                                     port_order,...
                                     symmetries_all,...
                                     matching_mask_detailed,...
                                     fixed_matching_mask_detailed,...
                                     fixed_matching_values,...
                                     tuning_mask_detailed,...
                                     mutual_mask_detailed,...
                                     matching_mask,...
                                     fixed_matching_mask,...
                                     tuning_mask,...
                                     mutual_mask,...
                                     unique_indices_all,...
                                     lower_bound_mat,...
                                     upper_bound_mat,...
                                     elems_after_matching,...
                                     options_PSO_2,...
                                     YPn,...
                                     emc,...
                                     fval_match);
    
    % Calibrate fields
    [M_cal,...
     YPm,...
     ZPm,...
     SPm] = calibration_tune_match_decouple(elements_after_tuning_matching_decoupling,...
                                            YPn,...
                                            symmetries_all,...
                                            all_fixed_matching_mask_detailed,...
                                            all_fixed_matching_values,...
                                            all_tuning_mask_detailed,...
                                            all_matching_mask,...
                                            all_fixed_matching_mask,...
                                            all_tuning_mask,...
                                            all_mutual_mask,...
                                            all_matching_load_string(:),...
                                            all_tuning_load_string,...
                                            all_port_order(:),...
                                            emc.omega,...
                                            emc.Z0);
    
    % Validate
    figure_freq = get_ZPm_Tx_freq(elements_after_tuning_matching_decoupling,...
                                  YPn,...
                                  symmetries_all,...
                                  all_matching_mask_detailed,...
                                  all_fixed_matching_mask_detailed,...
                                  all_fixed_matching_values,...
                                  all_tuning_mask_detailed,...
                                  all_matching_mask,...
                                  all_fixed_matching_mask,...
                                  all_tuning_mask,...
                                  all_mutual_mask,...
                                  all_matching_load_string(:),...
                                  all_tuning_load_string,...
                                  all_port_order(:),...
                                  emc.omega,...
                                  emc.Z0);

    return_elements = elements_after_tuning_matching_decoupling(symmetries_all);
    SP_check = [];

end