function[elems_after_matching,...
         matching_load_string,...
         tuning_load_string,...
         port_order,...
         symmetries_all,...
         fixed_matching_mask_detailed,...
         fixed_matching_values,...
         matching_mask_detailed,...
         tuning_mask_detailed,...
         mutual_mask_detailed,...
         unique_indices_all,...
         lower_bound_mat,...
         upper_bound_mat,...
         fval_min_return] = runner_M_T(RLC_tmd,...
                                       RLC_org,...
                                       tuning_elements,...
                                       mutual_elements,...
                                       elems_after_tuning,...
                                       coil_entity,...
                                       matching_mask,...
                                       fixed_matching_mask,...
                                       tuning_mask,...
                                       mutual_mask,...
                                       options_PSO_1,...
                                       YPn,...
                                       emc,...
                                       fval_tune)

    [symmetries_all,...
     port_order,...
     matching_load_string,...
     tuning_load_string,...
     symmetries,...
     matching_mask_detailed,...
     fixed_matching_mask_detailed,...
     fixed_matching_values,...
     tuning_mask_detailed,...
     mutual_mask_detailed,...
     lower_bound_mat,...
     upper_bound_mat,...
     unique_indices_all,...
     unique_indices] = co_simulation_matching_tuning_settings(RLC_tmd,...
                                                              RLC_org,...
                                                              tuning_elements,...
                                                              mutual_elements,...
                                                              elems_after_tuning,...
                                                              coil_entity, ...
                                                              fval_tune);
    
    elems_after_matching = zeros(length(unique_indices_all),1);
    fval_min_return = inf*ones(max(coil_entity,[],'all'),1);

    for i = 1:max(coil_entity)

        if isempty(unique_indices(i).id)
            continue
        end
    
        [y_ids,x_ids]                      = find(coil_entity == i);
        non_ids                            = setdiff(1:size(YPn, 1), y_ids);
        YPn_to_pass                        = YPn(y_ids,y_ids)-YPn(y_ids,non_ids)/YPn(non_ids,non_ids)*YPn(non_ids,y_ids);
        M_detailed                         = nonzeros(matching_mask_detailed(:,i));
        F_detailed                         = nonzeros(fixed_matching_mask_detailed(:,i));
        N_detailed                         = nonzeros(tuning_mask_detailed(:,i));
        [M_detailed,F_detailed,N_detailed] = map_to_local(M_detailed,F_detailed,N_detailed);
        MN_detailed                        = sort([M_detailed(:); N_detailed(:)]);
        MF_detailed                        = sort([M_detailed(:); F_detailed(:)]);
        M                                  = nonzeros(matching_mask(:,i));
        F                                  = nonzeros(fixed_matching_mask(:,i));
        N                                  = nonzeros(tuning_mask(:,i));
        D1                                 = nonzeros(mutual_mask(:,1,i));
        D2                                 = nonzeros(mutual_mask(:,2,i));
        D1                                 = ismember(N,D1);
        D2                                 = ismember(N,D2);
        [M,F,N]                            = map_to_local(M,F,N);
        FM                                 = sort([M(:); F(:)]);
        [M_new,~]                          = map_to_local_2(M,F);
        D1                                 = N(D1);
        D2                                 = N(D2);
        all_values                         = [D1 D2];                     
        [~, sort_idx]                      = sort(all_values);  
        ranks                              = zeros(size(all_values));           
        ranks(sort_idx)                    = 1:length(all_values); 
        mapped_D1                          = ranks(1:length(D1));
        mapped_D2                          = ranks(length(D1)+1:end);
        length_matching_network            = unique(max(port_order(i).id));
        idx12                              = sub2ind(size(YPn_to_pass), D1, D2);
        idx21                              = sub2ind(size(YPn_to_pass), D2, D1);
        fixed_elems                        = nonzeros(fixed_matching_values(:,i));

        costFun_match_tune = @(X) matching_and_tuning(X,...
                                                      YPn_to_pass,...
                                                      symmetries(i).id,...
                                                      M_detailed,...
                                                      F_detailed,...
                                                      fixed_elems,...
                                                      N_detailed,...
                                                      MN_detailed,...
                                                      MF_detailed,...
                                                      FM,...
                                                      M_new,...
                                                      N,...
                                                      idx12,...
                                                      idx21,...
                                                      mapped_D1,...
                                                      mapped_D2,...
                                                      length_matching_network,...
                                                      matching_load_string(i).id,...
                                                      tuning_load_string(i).id,...
                                                      port_order(i).id,...
                                                      emc.omega,...
                                                      emc.Z0);
        
        fval_min = inf;

        for counter_repeat = 1:10

            rng(counter_repeat);

            [X_final, fval, ~, ~] = particleswarm(costFun_match_tune,...
                                                  length(unique_indices(i).id),...
                                                  lower_bound_mat(unique_indices(i).id),...
                                                  upper_bound_mat(unique_indices(i).id),...
                                                  options_PSO_1);

            if fval < fval_min
                fval_min = fval;
                X_out = X_final;
                options_PSO_1.SwarmSize = min(options_PSO_1.SwarmSize+100,1000);
                options_PSO_1.MaxIterations = min(options_PSO_1.MaxIterations+100,1500);
                options_PSO_1.InertiaRange = [max(0.3,options_PSO_1.InertiaRange(1)-0.1) min(options_PSO_1.InertiaRange(2)+0.1,2.0)];
                options_PSO_1.SelfAdjustmentWeight = max(0.2,options_PSO_1.SelfAdjustmentWeight-0.1);
                options_PSO_1.SocialAdjustmentWeight = min(options_PSO_1.SocialAdjustmentWeight+0.1,2.5);
            end

            if fval_min < 1
                break
            end

        end
    
        if fval_min > 1
            fprintf('\t Coil %i is not Tuned and Matched, %4.6f.\n',i,fval_min);
        else
            fprintf('\t Coil %i is Tuned and Matched, %4.6f.\n',i,fval_min);
        end

        % Update in case elements are shared
        if fval_min > 1
            low_lv = 0.5;
            upp_lv = 1.5;
        else
            low_lv = 0.8;
            upp_lv = 1.2;
        end
        Xmin_raw                              = low_lv * X_out;
        Xmax_raw                              = upp_lv * X_out;
        X_min_fixed                           = max(min(min(Xmin_raw, Xmax_raw), 1), -1);
        X_max_fixed                           = max(min(max(Xmin_raw, Xmax_raw), 1), -1);
        lower_bound_mat(unique_indices(i).id) = X_min_fixed;
        upper_bound_mat(unique_indices(i).id) = X_max_fixed;

        elems_mapping = unique(symmetries_all(nonzeros(matching_mask_detailed(:,i)+tuning_mask_detailed(:,i)+mutual_mask_detailed(:,i))));
        elems_after_matching(elems_mapping) = X_out;
        elems_after_matching(nonzeros(fixed_matching_mask_detailed(:,i))) = nan*fixed_elems;
        fval_min_return(i) = fval_min;
    
    end

end