function[X_out,...
         all_matching_load_string,...
         all_port_order,...
         all_tuning_load_string,...
         all_tuning_mask_detailed,...
         all_matching_mask_detailed,...
         all_fixed_matching_mask_detailed,...
         all_fixed_matching_values,...
         all_matching_mask,...
         all_fixed_matching_mask,...
         all_tuning_mask,...
         all_mutual_mask,...
         symmetries_all] = runner_M_T_PD(matching_load_string,...
                                         tuning_load_string,...
                                         port_order,...
                                         symmetries_all,...
                                         matching_mask_detailed,...
                                         fixed_matching_mask_detailed,...
                                         fixed_matching_values,...
                                         tuning_mask_detailed,...
                                         mutual_mask_detailed,...
                                         matching_mask,...
                                         fixed_matching_mask,...
                                         tuning_mask,...
                                         mutual_mask,...
                                         unique_indices_all,...
                                         lower_bound_mat,...
                                         upper_bound_mat,...
                                         elems_after_matching,...
                                         options_PSO_2,...
                                         YPn,...
                                         emc,...
                                         fval_match)


    fval_match = sum(fval_match);
    if fval_match > 1
        low_lv = 0.5;
        upp_lv = 1.5;
    else
        low_lv = 0.95;
        upp_lv = 1.05;
    end

    [all_matching_load_string,...
     all_port_order,...
     all_tuning_load_string,...
     all_tuning_mask_detailed,...
     all_matching_mask_detailed,...
     all_fixed_matching_mask_detailed,...
     all_fixed_matching_values,...
     all_matching_mask,...
     all_fixed_matching_mask,...
     all_tuning_mask,...
     all_mutual_mask] = co_simulation_matching_tuning_decoupling_settings(matching_load_string,...
                                                                          tuning_load_string,...
                                                                          port_order,...
                                                                          tuning_mask_detailed,...
                                                                          mutual_mask_detailed,...
                                                                          matching_mask_detailed,...
                                                                          fixed_matching_mask_detailed,...
                                                                          fixed_matching_values,...
                                                                          matching_mask,...
                                                                          fixed_matching_mask,...
                                                                          tuning_mask,...
                                                                          mutual_mask);

    if length([nonzeros(all_matching_mask);nonzeros(all_fixed_matching_mask)])>1

        M                                  = nonzeros(all_matching_mask);
        F                                  = nonzeros(all_fixed_matching_mask);
        N                                  = nonzeros(all_tuning_mask);
        D1                                 = nonzeros(all_mutual_mask(:,1));
        D2                                 = nonzeros(all_mutual_mask(:,2));
        D1                                 = ismember(N,D1);
        D2                                 = ismember(N,D2);
        [M,F,N]                            = map_to_local(M,F,N);
        FM                                 = sort([M(:); F(:)]);
        [M_new,~]                          = map_to_local_2(M,F);
        D1                                 = N(D1);
        D2                                 = N(D2);
        all_values                         = [D1 D2];                     
        [~, sort_idx]                      = sort(all_values);  
        ranks                              = zeros(size(all_values));           
        ranks(sort_idx)                    = 1:length(all_values); 
        mapped_D1                          = ranks(1:length(D1));
        mapped_D2                          = ranks(length(D1)+1:end);
        length_matching_network            = unique(max(all_port_order(:)));
        idx12                              = sub2ind(size(YPn), D1, D2);
        idx21                              = sub2ind(size(YPn), D2, D1);
        M_detailed                         = nonzeros(all_matching_mask_detailed);
        F_detailed                         = nonzeros(all_fixed_matching_mask_detailed);
        N_detailed                         = nonzeros(all_tuning_mask_detailed);
        [M_detailed,F_detailed,N_detailed] = map_to_local(M_detailed,F_detailed,N_detailed);
        MN_detailed                        = sort([M_detailed(:); N_detailed(:)]);
        MF_detailed                        = sort([M_detailed(:); F_detailed(:)]);
        symmetries_all(F_detailed)         = [];
        [unique_vals, ~, new_indices]      = unique(nonzeros(symmetries_all), 'stable'); 
        new_mapping                        = 1:length(unique_vals);
        symmetries_all                     = new_mapping(new_indices);

        costFun_match_tune_preamplifierdecoupling = @(X) matching_and_tuning_and_preamplifierdecoupling(X,...
                                                                                                        YPn,...
                                                                                                        symmetries_all,...
                                                                                                        M_detailed,...
                                                                                                        F_detailed,...
                                                                                                        N_detailed,...
                                                                                                        MN_detailed,...
                                                                                                        MF_detailed,...
                                                                                                        all_fixed_matching_values,...
                                                                                                        FM,...
                                                                                                        M_new,...
                                                                                                        N,...
                                                                                                        idx12,...
                                                                                                        idx21,...
                                                                                                        mapped_D1,...
                                                                                                        mapped_D2,...
                                                                                                        length_matching_network,...
                                                                                                        all_matching_load_string(:),...
                                                                                                        all_tuning_load_string,...
                                                                                                        all_port_order(:),...
                                                                                                        emc.omega,...
                                                                                                        emc.Z0,...
                                                                                                        emc.Preamp_res);
        
        fval_min = inf;
        if fval_match > 1
            X_min_fixed = rmmissing(lower_bound_mat(unique_indices_all));
            X_max_fixed = rmmissing(upper_bound_mat(unique_indices_all));
        else
            Xmin_raw = low_lv * rmmissing(elems_after_matching);
            Xmax_raw = upp_lv * rmmissing(elems_after_matching);
            X_min_fixed = max(min(min(Xmin_raw, Xmax_raw), 1), -1);
            X_max_fixed = max(min(max(Xmin_raw, Xmax_raw), 1), -1);
        end

        for counter_repeat = 1:1
            if fval_min < 1
                break
            end
            rng(counter_repeat);

            [X_final, fval, ~, ~] = particleswarm(costFun_match_tune_preamplifierdecoupling,...
                                                  length(X_min_fixed),...
                                                  X_min_fixed,...
                                                  X_max_fixed,...
                                                  options_PSO_2);  

            if fval<fval_min
                fval_min = fval;
                X_out = X_final;
                options_PSO_2.SwarmSize = min(options_PSO_2.SwarmSize+100,1000);
                options_PSO_2.MaxIterations = min(options_PSO_2.MaxIterations+10,1500);
                options_PSO_2.InertiaRange = [max(0.3,options_PSO_2.InertiaRange(1)-0.1) min(options_PSO_2.InertiaRange(2)+0.1,2.0)];
                options_PSO_2.SelfAdjustmentWeight = max(0.2,options_PSO_2.SelfAdjustmentWeight-0.1);
                options_PSO_2.SocialAdjustmentWeight = min(options_PSO_2.SocialAdjustmentWeight+0.1,2.5);
                Xmin_raw = low_lv * X_final;
                Xmax_raw = upp_lv * X_final;
                X_min_fixed = max(min(min(Xmin_raw, Xmax_raw), 1), -1);
                X_max_fixed = max(min(max(Xmin_raw, Xmax_raw), 1), -1);
            end  

            if fval_min < 1
                break
            end               
        end

    else
        X_out = elems_after_matching;
    end

end