function[figure_freq] = get_ZPm_TxRx_and_TxRx_freq(X,...
                                                   YPn,...
                                                   symmetries,...
                                                   match_split,...
                                                   mask_detailed_split,...
                                                   matching_mask_detailed,...
                                                   fixed_matching_mask_detailed,...
                                                   fixed_matching_elements,...
                                                   tuning_mask_detailed,...
                                                   matching_mask,...
                                                   fixed_matching_mask,...            
                                                   tuning_mask,...
                                                   mutual_mask,...
                                                   matching_load_string,...
                                                   tuning_load_string,...
                                                   port_order,...
                                                   omega,...
                                                   z0, ...
                                                   preamp_res,...
                                                   detune_res,...
                                                   Q_val)

    freq                 = omega/(2*pi);
    freq_range           = linspace(freq * 0.8, freq * 1.2, 5000); 
    [~, freq_idx]        = min(abs(freq_range - freq)); 
    freq_range(freq_idx) = freq; 
    omega_range          = freq_range*2*pi;

    M                                  = nonzeros(matching_mask);
    F                                  = nonzeros(fixed_matching_mask);
    N                                  = nonzeros(tuning_mask);
    D1                                 = nonzeros(mutual_mask(:,1));
    D2                                 = nonzeros(mutual_mask(:,2));
    D1                                 = ismember(N,D1);
    D2                                 = ismember(N,D2);
    [M,F,N]                            = map_to_local(M,F,N);
    M                                  = sort([M(:); F(:)]);
    D1                                 = N(D1);
    D2                                 = N(D2);
    all_values                         = [D1 D2];                     
    [~, sort_idx]                      = sort(all_values);  
    ranks                              = zeros(size(all_values));           
    ranks(sort_idx)                    = 1:length(all_values); 
    mapped_D1                          = ranks(1:length(D1));
    mapped_D2                          = ranks(length(D1)+1:end);
    length_matching_network            = unique(max(port_order(:)));
    M_detailed                         = nonzeros(matching_mask_detailed);
    F_detailed                         = nonzeros(fixed_matching_mask_detailed);
    N_detailed                         = nonzeros(tuning_mask_detailed);
    [M_detailed,F_detailed,N_detailed] = map_to_local(M_detailed,F_detailed,N_detailed);
    MN_detailed                        = sort([M_detailed(:); N_detailed(:)]);
    MF_detailed                        = sort([M_detailed(:); F_detailed(:)]);

    lumped_elements                  = X(symmetries); 
    Rx_elems_match                   = mask_detailed_split==1 | mask_detailed_split==3;
    Tx_elems_match                   = mask_detailed_split==2 | mask_detailed_split==3;
    RxM                              = match_split==1 | match_split==3;
    RxM_det                          = match_split==1;
    TxM                              = match_split==2 | match_split==3;
    TxM_det                          = match_split==2;
    all_elements                     = zeros(numel(M_detailed)+numel(F_detailed)+numel(N_detailed),1);
    all_elements(MN_detailed)        = lumped_elements;
    all_elements(F_detailed)         = nonzeros(fixed_matching_elements);
    true_tuning_elements             = all_elements(N_detailed);
    Q_true_tuning_elements           = Q_val(N_detailed);
    matching_elementsRx              = all_elements(MF_detailed(Rx_elems_match(MF_detailed)));
    matching_elementsTx              = all_elements(MF_detailed(Tx_elems_match(MF_detailed)));
    Q_matching_elementsRx            = Q_val(MF_detailed(Rx_elems_match(MF_detailed)));
    Q_matching_elementsTx            = Q_val(MF_detailed(Tx_elems_match(MF_detailed)));
    matching_load_stringRx           = matching_load_string(:,RxM);
    matching_load_stringTx           = matching_load_string(:,TxM);
    port_orderRx                     = port_order(:,RxM);
    port_orderRx                     = port_orderRx(:);
    port_orderTx                     = port_order(:,TxM);
    port_orderTx                     = port_orderTx(:);
    is_capacitor_parallelRx          = strcmpi(matching_load_stringRx(:), 'capacitorParallel');
    is_inductor_parallelRx           = strcmpi(matching_load_stringRx(:), 'inductorParallel');
    is_resistor_parallelRx           = strcmpi(matching_load_stringRx(:), 'resistorParallel');
    is_capacitor_seriesRx            = strcmpi(matching_load_stringRx(:), 'capacitorSeries');
    is_inductor_seriesRx             = strcmpi(matching_load_stringRx(:), 'inductorSeries');
    is_resistor_seriesRx             = strcmpi(matching_load_stringRx(:), 'resistorSeries');
    is_capacitor_parallelTx          = strcmpi(matching_load_stringTx(:), 'capacitorParallel');
    is_inductor_parallelTx           = strcmpi(matching_load_stringTx(:), 'inductorParallel');
    is_resistor_parallelTx           = strcmpi(matching_load_stringTx(:), 'resistorParallel');
    is_capacitor_seriesTx            = strcmpi(matching_load_stringTx(:), 'capacitorSeries');
    is_inductor_seriesTx             = strcmpi(matching_load_stringTx(:), 'inductorSeries');
    is_resistor_seriesTx             = strcmpi(matching_load_stringTx(:), 'resistorSeries');
    is_capacitor                     = strcmpi(tuning_load_string, 'capacitor');
    is_inductor                      = strcmpi(tuning_load_string, 'inductor');
    is_resistor                      = strcmpi(tuning_load_string, 'resistor');
    is_mutual_inductor               = strcmpi(tuning_load_string, 'mutual_inductor');
    is_mutual_inductance_coefficient = strcmpi(tuning_load_string, 'mutual_inductance_coefficient');
    mutual_inductance_coefficients   = lumped_elements(end-sum(is_mutual_inductance_coefficient)+1:end);
    mutual_inductances               = true_tuning_elements(is_mutual_inductor);

    ZPm_plot_Rx = zeros(size(nonzeros(RxM),1),size(nonzeros(RxM),1),length(freq_range));
    SPm_plot_Rx = zeros(size(nonzeros(RxM),1),size(nonzeros(RxM),1),length(freq_range));
    ZPm_plot_Tx = zeros(size(nonzeros(TxM),1),size(nonzeros(TxM),1),length(freq_range));
    SPm_plot_Tx = zeros(size(nonzeros(TxM),1),size(nonzeros(TxM),1),length(freq_range));

    for freq_id = 1:length(freq_range)

        [YPm,~,~] = tune(true_tuning_elements,...
                         omega_range(freq_id),...
                         Q_true_tuning_elements,...
                         is_capacitor,...
                         is_inductor,...
                         is_mutual_inductor,...
                         is_resistor,...
                         YPn,...
                         D1,...
                         D2,...
                         mutual_inductance_coefficients,...
                         mutual_inductances,...
                         mapped_D1,...
                         mapped_D2,...
                         N,...
                         M);

        % Apply detuning
        Rxdet = 1/detune_res*eye(size(nonzeros(RxM_det),1));
        Txdet = 1/detune_res*eye(size(nonzeros(TxM_det),1));
   
        % Switch to de-tuned mode
        YPm_Rx = YPm(RxM,RxM)-YPm(RxM,TxM_det)/(YPm(TxM_det,TxM_det)+Txdet)*YPm(TxM_det,RxM);
        YPm_Tx = YPm(TxM,TxM)-YPm(TxM,RxM_det)/(YPm(RxM_det,RxM_det)+Rxdet)*YPm(RxM_det,TxM);
    
        % Model preamplifier effect
        [~,~,SP_check,ZP_check,~] = preamplifier_match(YPm_Rx,...
                                                       YPm_Rx,...
                                                       preamp_res,...
                                                       z0,...
                                                       length_matching_network,...
                                                       port_orderRx,...
                                                       is_capacitor_parallelRx,...
                                                       is_inductor_parallelRx,...
                                                       is_resistor_parallelRx,...
                                                       is_capacitor_seriesRx,...
                                                       is_inductor_seriesRx,...
                                                       is_resistor_seriesRx,...
                                                       matching_elementsRx,...
                                                       Q_matching_elementsRx,...
                                                       omega_range(freq_id));
        
        ZPm_plot_Rx(:,:,freq_id) = diag(ZP_check);
        SPm_plot_Rx(:,:,freq_id) = diag(SP_check);

        % Matching Elements without Preamps
        [SPm_Tx,ZPm_Tx,~] = match(YPm_Tx,...
                                  YPm_Tx,...
                                  z0,...
                                  length_matching_network,...
                                  port_orderTx,...
                                  is_capacitor_parallelTx,...
                                  is_inductor_parallelTx,...
                                  is_resistor_parallelTx,...
                                  is_capacitor_seriesTx,...
                                  is_inductor_seriesTx,...
                                  is_resistor_seriesTx,...
                                  matching_elementsTx,...
                                  Q_matching_elementsTx,...
                                  omega_range(freq_id));

        ZPm_plot_Tx(:,:,freq_id) = ZPm_Tx;
        SPm_plot_Tx(:,:,freq_id) = SPm_Tx;

    end

    figure_freq.ZPm_plot_Rx = ZPm_plot_Rx;
    figure_freq.SPm_plot_Rx = SPm_plot_Rx;
    figure_freq.ZPm_plot_Tx = ZPm_plot_Tx;
    figure_freq.SPm_plot_Tx = SPm_plot_Tx;
    figure_freq.freq_range  = freq_range;
    figure_freq.freq_idx    = freq_idx;
    
end