function [M_cal,...
          phi_lumped_elements,...
          YPm_Tx,...
          ZPm,...
          SPm,...
          SP_check] = calibration_match_Tx_decouple_and_Rx_preampdecouple(matching_elements,...
                                                                          YPm,...
                                                                          match_split,...
                                                                          mask_detailed_split,...
                                                                          matching_load_string,...
                                                                          port_order,...
                                                                          omega,...
                                                                          z0,...
                                                                          preamp_res,...
                                                                          detune_res,...
                                                                          Q_val)
    
    Rx_elems_match                   = mask_detailed_split==1;
    Tx_elems_match                   = mask_detailed_split==2;
    matching_elementsRx              = matching_elements(Rx_elems_match);
    matching_elementsTx              = matching_elements(Tx_elems_match);
    Q_valRx                          = Q_val(Rx_elems_match);
    Q_valTx                          = Q_val(Tx_elems_match);
    RxM                              = match_split==1;
    TxM                              = match_split==2;
    matching_load_stringRx           = matching_load_string(Rx_elems_match);
    matching_load_stringTx           = matching_load_string(Tx_elems_match);
    port_orderRx                     = port_order(Rx_elems_match);
    port_orderTx                     = port_order(Tx_elems_match);
    is_capacitor_parallelRx          = strcmpi(matching_load_stringRx(:), 'capacitorParallel');
    is_inductor_parallelRx           = strcmpi(matching_load_stringRx(:), 'inductorParallel');
    is_resistor_parallelRx           = strcmpi(matching_load_stringRx(:), 'resistorParallel');
    is_capacitor_seriesRx            = strcmpi(matching_load_stringRx(:), 'capacitorSeries');
    is_inductor_seriesRx             = strcmpi(matching_load_stringRx(:), 'inductorSeries');
    is_resistor_seriesRx             = strcmpi(matching_load_stringRx(:), 'resistorSeries');
    is_capacitor_parallelTx          = strcmpi(matching_load_stringTx(:), 'capacitorParallel');
    is_inductor_parallelTx           = strcmpi(matching_load_stringTx(:), 'inductorParallel');
    is_resistor_parallelTx           = strcmpi(matching_load_stringTx(:), 'resistorParallel');
    is_capacitor_seriesTx            = strcmpi(matching_load_stringTx(:), 'capacitorSeries');
    is_inductor_seriesTx             = strcmpi(matching_load_stringTx(:), 'inductorSeries');
    is_resistor_seriesTx             = strcmpi(matching_load_stringTx(:), 'resistorSeries');

    length_matching_network = unique(max(port_order));

    % Apply detuning
    Rxdet = 1/detune_res*eye(size(nonzeros(RxM),1));
    Txdet = 1/detune_res*eye(size(nonzeros(TxM),1));
    YPm_Rx = YPm;
    YPm_Rx(TxM,TxM) = YPm_Rx(TxM,TxM)+Txdet;
    ZPn_Rx = inv(YPm_Rx);
    YPm_Tx = YPm;
    YPm_Tx(RxM,RxM) = YPm_Rx(RxM,RxM)+Rxdet;
    ZPn_Tx = inv(YPm_Tx);
    
    MRx                      = size(nonzeros(RxM),1);
    M_detune_Rx              = zeros(size(YPm,1),MRx);
    M_detune_Rx(RxM,1:MRx)   = ZPn_Rx(RxM,RxM);
    M_detune_Rx(TxM,1:MRx)   = ZPn_Rx(TxM,RxM);
    M_detune_Rx              = M_detune_Rx/ZPn_Rx(RxM,RxM);
    MTx                      = size(nonzeros(TxM),1);
    M_detune_Tx              = zeros(size(YPm,1),MTx);
    M_detune_Tx(TxM,1:MTx)   = ZPn_Tx(TxM,TxM);
    M_detune_Tx(RxM,1:MTx)   = ZPn_Tx(RxM,TxM);
    M_detune_Tx              = M_detune_Tx/ZPn_Tx(TxM,TxM);

    % Switch to de-tuned mode
    YPm_Rx = YPm(RxM,RxM)-YPm(RxM,TxM)/(YPm(TxM,TxM)+Txdet)*YPm(TxM,RxM);
    YPm_Tx = YPm(TxM,TxM)-YPm(TxM,RxM)/(YPm(RxM,RxM)+Rxdet)*YPm(RxM,TxM);

    YPm_loss_Rx = YPm_Rx;
    YPm_loss_Tx = YPm_Tx;

    % Model preamplifier effect
    [M_match_Rx,...
     M_decouple_Rx,...
     SP_check,...
     ZP_check,...
     ZP_check_loss] = preamplifier_match(YPm_Rx,...
                                         YPm_loss_Rx,...
                                         preamp_res,...
                                         z0,...
                                         length_matching_network,...
                                         port_orderRx,...
                                         is_capacitor_parallelRx,...
                                         is_inductor_parallelRx,...
                                         is_resistor_parallelRx,...
                                         is_capacitor_seriesRx,...
                                         is_inductor_seriesRx,...
                                         is_resistor_seriesRx,...
                                         matching_elementsRx,...
                                         Q_valRx,...
                                         omega);

    SPs = np_z2s(inv(YPm_Tx),z0);
    % Model matching elements
    [SPm,ZPm,ZPm_loss] = match(YPm_Tx,...
                               YPm_loss_Tx,...
                               z0,...
                               length_matching_network,...
                               port_orderTx,...
                               is_capacitor_parallelTx,...
                               is_inductor_parallelTx,...
                               is_resistor_parallelTx,...
                               is_capacitor_seriesTx,...
                               is_inductor_seriesTx,...
                               is_resistor_seriesTx,...
                               matching_elementsTx,...
                               Q_valTx,...
                               omega);   

    M_cal.rx = (M_detune_Rx*M_decouple_Rx)*M_match_Rx;
    M_cal.tx = M_detune_Tx*calibration_matching(SPs,SPm,z0);
    
    phi_lumped_elements.Tx = diag(1/2*diag(abs(real(ZPm_loss-ZPm))).*(1./abs(diag(ZPm))).^2);
    phi_lumped_elements.Rx = 1/2*diag(abs(real(ZP_check_loss-ZP_check))).*(1./abs(diag(ZP_check))).^2;
    phi_lumped_elements.Rx(isnan(phi_lumped_elements.Rx)) = 0;

end
